---
abstract: 'Generate HTML representations of Data Matrix barcodes'
author:
  - 'Mark A. Stratman, C<< <stratman@gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Barcode-DataMatrix
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.15
  Barcode::DataMatrix: 0.01
  HTML::Barcode: 0.09
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mstratman/HTML-Barcode-DataMatrix.git
version: 0.03
